MIN_STRING = 1
MAX_STRING = 100
FORMAT = '%Y/%m/%d %H:%M:%S'
VERSION_SHEETS = 'v4'
VERSION_DRIVE = 'v3'
SHEET_ID = 0
TITLE_CLOSE_SPEED = 'Скорость закрытия'
ROW_COUNT = 100
COLUMN_COUNT = 11
LOCALE = 'ru_RU'

METHOD_NOT_ALLOWED = 405
BAD_REQUEST = 400
NOT_FOUND = 404
